### ISSUE TITLE
Wrong cursor placement when switching from grammar selection to command palette & vice versa

### ISSUE THREAD

**Issue by Aerijo** [atom/command-palette#107] opened 2018-02-18 04:09 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When manually selecting a grammar in the grammar selection menu (GS), the cursor is automatically placed in the search box. This also happens with the command palette (CP).

However, when switching directly from GS to CP, the cursor is not placed in the CP. Instead, it is placed on the file behind the palette. This cursor behaves normally, and all keyboard bindings behave as if the file were properly visible as well. Unfortunately, this includes the escape key, so the CP cannot even be closed like normal.

Interacting with the CP requires either clicking the search box, which places the cursor in it, or using the shortcut for the command palatte (which closes it). Going back to the GS menu via the shortcut also hides it, and the cursor is correctly positioned in the search box.

I'm opening this here, but the behaviour is the same when the opposite happens (CP to GS).

### Steps to Reproduce

1. Open atom in safe mode
2. Open a new file
3. Use the shortcut to open the gramar menu (`cmd-shift-L` on macOS)
4. Use the shortcut to open the command palette (`cmd-shift-P` on macOS)

**Expected behavior:**
The cursor is placed in the search box of the command palette

**Actual behavior:**
The cursor goes to the file behind the box. Looking closely, it can be seen moving and acting otherwise normally when typing, as if the command palette was not open.

**Reproduces how often:**
100%

### Versions
```
Atom    : 1.23.3
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.23.3
python 2.7.10
git 2.14.3

macOS 10.13.3
```

**Comment by Ben3eeE** [comment] 2018-02-19 09:50
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/14325. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Ben3eeE** 2018-02-19 09:50 UTC
Labels: duplicate
