### ISSUE TITLE
cmd-shift-P not working on macbook

### ISSUE THREAD

**Issue by zacharyrs** [atom/command-palette#91] opened 2017-10-23 20:52 UTC
### Prerequisites
 * [X] Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
 * [X] Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
 * [X] Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
 * [X] Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
 * [X] Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Can't open the command palette via default shortcut on MacBookPro, can on iMac.
Same packages and config.

### Steps to Reproduce
1. Launch atom
2. Try to open command palette (via cmd-shift-P)

**Expected behaviour:** Command palette should open.

**Actual behaviour:** Nothing happens.

**Reproduces how often:** Every time.

### Versions
Atom    : 1.21.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
macOS 10.13, MacBookPro

### Additional Information
Zilch, although you can view my config [here](https://gist.github.com/zacharyrs/2f9ed472a2860242bc6c1a668bb60477).

**Comment by rsese** [comment] 2017-10-24 04:22
Thanks for the report - I'm unable to reproduce with Atom 1.21.1 in safe mode on macOS 10.12.6.

Can you share a screenshot of what you see with the [keyboard resolver](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-your-keybindings) active while typing <kbd>cmd-shift-p</kbd>?

**Comment by zacharyrs** [comment] 2017-10-24 05:23
Hi there, not on my laptop right now, but I did try that earlier.

It seems to never pick up the `P`, only showing `cmd-shift`. I guess I must have something that hijacks the key combo?

The odd thing is I run the exact same software on both...

**Comment by Ben3eeE** [comment] 2017-10-24 05:25
> I guess I must have something that hijacks the key combo?

Yes when this happens you have some other application running that is responding to the keystroke.

**Comment by zacharyrs** [comment] 2017-10-24 05:27
Yeah, shame there's no easy way to tell which one.

I did try with everything but atom quit, including my menubar things, but no dice.

**Comment by rsese** [comment] 2017-10-24 17:57
I haven't used it but in another case where a key combo wasn't working, someone in the community mentioned the app they used to track down the culprit:

https://discuss.atom.io/t/strange-key-binding-behavior-only-alt-cmd-z-combo/43374/2

We'll go ahead and close this for now but if you find there's a problem with Atom, please let us know and we can re-open.

**Closed by rsese** 2017-10-24 17:57 UTC
Labels: more-information-needed

**Comment by GreatWizard** [comment] 2021-03-26 16:56
On MacOS, I have the same issue today.
This is not related to atom but the entire OS. I can't use cmd + shift + P in all my apps... I'm still digging what global configuration bind this shortcut.

**Comment by 0xbs0d** [comment] 2021-08-31 21:35
@GreatWizard Thank you so much for this. It was driving me crazy. Btw the latest versions of Keeper let you change the shortcut. Tnx again!
