### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by foikila** [atom/command-palette#47] opened 2015-06-17 12:06 UTC
This occurred when I had a "markdown preview" toggled in fullscreen and then tried to open a new pane on top of it.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Ubuntu 14.04.2
**Thrown From**: [command-palette](https://github.com/atom/command-palette) package, v0.36.0

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /usr/share/atom/resources/app.asar/src/pane.js:604

Error: Pane has been destroyed
  at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:604:15)
  at Pane.module.exports.Pane.split (/usr/share/atom/resources/app.asar/src/pane.js:689:15)
  at Pane.module.exports.Pane.splitRight (/usr/share/atom/resources/app.asar/src/pane.js:653:19)
  at atom-pane.atom.commands.add.pane:split-right (/usr/share/atom/resources/app.asar/src/pane-element.js:270:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
  2x -1:53.7.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:52.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:49.4.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:47.8.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -1:47.2.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -1:46.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:42.5.0 core:delete (atom-text-editor.editor.is-focused)
     -1:42.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:39.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:38.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:05.6.0 bracket-matcher:remove-brackets-from-selection (div.markdown-preview.native-key-bindings)
     -0:04.3.0 command-palette:toggle (div.markdown-preview.native-key-bindings)
     -0:02.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.2.0 pane:split-right (div.markdown-preview.native-key-bindings)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
block-travel, v1.0.2
linter, v0.12.7
linter-csslint, v0.0.13
linter-htmlhint, v0.0.16
linter-jscs, v1.12.0
linter-jshint, v0.1.6
linter-less, v0.5.0
linter-pep8, v0.2.0
linter-php, v0.0.15
linter-phpcs, v0.0.15
linter-phpmd, v0.0.11
linter-pylint, v0.2.2
linter-shellcheck, v0.0.8
linter-xmllint, v0.0.6
remote-edit, v1.8.2

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment] 2016-10-07 18:14
Closing as a duplicate of https://github.com/atom/atom/issues/8652.

**Closed by Ben3eeE** 2016-10-07 18:14 UTC
Labels: bug, uncaught-exception
